import React, { useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import semaphoreABI from '../abi/semaphoreABI.json';
import CreateGroup from '../components/CreateGroup';
import AddMember from '../components/AddMember';
import VerifyProof from '../components/VerifyProof';
import Keypair from '../components/Keypair';

const contract = {
  address: '0xbe5aaa6da0445d4a9989702e0fb8b590039112f1',
  chain: 17000,
  abi: semaphoreABI,
};

const Home: NextPage = () => {
  const [groupId, setGroupId] = useState(1);
  const [idSeed, setIdSeed] = useState(null);
  const [keypair, setKeypair] = useState(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js</a> + <a href="https://github.com/numtel/zk-group-decryptable">Semaphore Decryptable</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>1. Create Group</h2>
            <CreateGroup {...{contract, groupId, setGroupId}} />
          </div>
          <div className={styles.card}>
            <h2>2. Add Member</h2>
            <AddMember {...{contract, groupId, setIdSeed, idSeed}} />
          </div>
          <div className={styles.card}>
            <h2>3. Generate Keypair</h2>
            <Keypair {...{keypair, setKeypair}} />
          </div>
          <div className={styles.card}>
            <h2>4. Verify Proof</h2>
            <VerifyProof {...{contract, groupId, idSeed, keypair}} />
          </div>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
